//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemAdmin.Localization.SystemBasicMgmt.UserSettings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemAdmin.Localization.SystemBasicMgmt.UserSettings.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 代理用户已代理其他用户，不可多人员代理 的本地化字符串。
        /// </summary>
        internal static string HasMultipleTargets {
            get {
                return ResourceManager.GetString("HasMultipleTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代理用户已被其他用户代理，不能作为代理用户 的本地化字符串。
        /// </summary>
        internal static string UserAgentAlreadyAgented {
            get {
                return ResourceManager.GetString("UserAgentAlreadyAgented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代理关系删除失败 的本地化字符串。
        /// </summary>
        internal static string UserAgentDeleteFailed {
            get {
                return ResourceManager.GetString("UserAgentDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代理关系删除成功 的本地化字符串。
        /// </summary>
        internal static string UserAgentDeleteSuccess {
            get {
                return ResourceManager.GetString("UserAgentDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代理配置失败 的本地化字符串。
        /// </summary>
        internal static string UserAgentInsertFailed {
            get {
                return ResourceManager.GetString("UserAgentInsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代理配置成功 的本地化字符串。
        /// </summary>
        internal static string UserAgentInsertSuccess {
            get {
                return ResourceManager.GetString("UserAgentInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 被代理用户与代理用户不能为同一人 的本地化字符串。
        /// </summary>
        internal static string UserAgentSameUser {
            get {
                return ResourceManager.GetString("UserAgentSameUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 被代理用户已被其他用户代理，不可多人员代理 的本地化字符串。
        /// </summary>
        internal static string UserAgentTargetAlreadyAgented {
            get {
                return ResourceManager.GetString("UserAgentTargetAlreadyAgented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 被代理用户已代理其他用户，不能嵌套代理 的本地化字符串。
        /// </summary>
        internal static string UserAgentTargetHasAgentRole {
            get {
                return ResourceManager.GetString("UserAgentTargetHasAgentRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置失败 的本地化字符串。
        /// </summary>
        internal static string UserFormUpdateFailed {
            get {
                return ResourceManager.GetString("UserFormUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置成功 的本地化字符串。
        /// </summary>
        internal static string UserFormUpdateSuccess {
            get {
                return ResourceManager.GetString("UserFormUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户兼任删除失败 的本地化字符串。
        /// </summary>
        internal static string UserPartTimeDeleteFailed {
            get {
                return ResourceManager.GetString("UserPartTimeDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户兼任删除成功 的本地化字符串。
        /// </summary>
        internal static string UserPartTimeDeleteSuccess {
            get {
                return ResourceManager.GetString("UserPartTimeDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户兼任新增失败 的本地化字符串。
        /// </summary>
        internal static string UserPartTimeInsertFailed {
            get {
                return ResourceManager.GetString("UserPartTimeInsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户兼任新增成功 的本地化字符串。
        /// </summary>
        internal static string UserPartTimeInsertSuccess {
            get {
                return ResourceManager.GetString("UserPartTimeInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该用户已在此部门兼任该职业，无法重复设置 的本地化字符串。
        /// </summary>
        internal static string UserPartTimeIsExist {
            get {
                return ResourceManager.GetString("UserPartTimeIsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户兼任修改失败 的本地化字符串。
        /// </summary>
        internal static string UserPartTimeUpdateFailed {
            get {
                return ResourceManager.GetString("UserPartTimeUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户兼任修改成功 的本地化字符串。
        /// </summary>
        internal static string UserPartTimeUpdateSuccess {
            get {
                return ResourceManager.GetString("UserPartTimeUpdateSuccess", resourceCulture);
            }
        }
    }
}
