//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemAdmin.Localization.SystemBasicMgmt.SystemBasicData {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemAdmin.Localization.SystemBasicMgmt.SystemBasicData.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 部门信息删除成功 的本地化字符串。
        /// </summary>
        internal static string DeptInfoDeleteSuccess {
            get {
                return ResourceManager.GetString("DeptInfoDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门代码已存在，请重新输入 的本地化字符串。
        /// </summary>
        internal static string DeptInfoDeptCodeExist {
            get {
                return ResourceManager.GetString("DeptInfoDeptCodeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门信息新增失败 的本地化字符串。
        /// </summary>
        internal static string DeptInfoInsertFailed {
            get {
                return ResourceManager.GetString("DeptInfoInsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门信息新增成功 的本地化字符串。
        /// </summary>
        internal static string DeptInfoInsertSuccess {
            get {
                return ResourceManager.GetString("DeptInfoInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法删除部门，因为该部门或其子部门下存在人员 的本地化字符串。
        /// </summary>
        internal static string DeptInfoNotDelete {
            get {
                return ResourceManager.GetString("DeptInfoNotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门信息修改失败 的本地化字符串。
        /// </summary>
        internal static string DeptInfoUpdateFailed {
            get {
                return ResourceManager.GetString("DeptInfoUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门信息修改成功 的本地化字符串。
        /// </summary>
        internal static string DeptInfoUpdateSuccess {
            get {
                return ResourceManager.GetString("DeptInfoUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门层级删除失败 的本地化字符串。
        /// </summary>
        internal static string DeptLevelDeleteFailed {
            get {
                return ResourceManager.GetString("DeptLevelDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门层级删除成功 的本地化字符串。
        /// </summary>
        internal static string DeptLevelDeleteSuccess {
            get {
                return ResourceManager.GetString("DeptLevelDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门层级新增失败 的本地化字符串。
        /// </summary>
        internal static string DeptLevelInsertFailed {
            get {
                return ResourceManager.GetString("DeptLevelInsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门层级新增成功 的本地化字符串。
        /// </summary>
        internal static string DeptLevelInsertSuccess {
            get {
                return ResourceManager.GetString("DeptLevelInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门层级修改失败 的本地化字符串。
        /// </summary>
        internal static string DeptLevelUpdateFailed {
            get {
                return ResourceManager.GetString("DeptLevelUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门层级修改成功 的本地化字符串。
        /// </summary>
        internal static string DeptLevelUpdateSuccess {
            get {
                return ResourceManager.GetString("DeptLevelUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 国籍信息删除失败 的本地化字符串。
        /// </summary>
        internal static string NationalityInfoDeleteFailed {
            get {
                return ResourceManager.GetString("NationalityInfoDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 国籍信息删除成功 的本地化字符串。
        /// </summary>
        internal static string NationalityInfoDeleteSuccess {
            get {
                return ResourceManager.GetString("NationalityInfoDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 国籍信息新增失败 的本地化字符串。
        /// </summary>
        internal static string NationalityInfoInsertFailed {
            get {
                return ResourceManager.GetString("NationalityInfoInsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 国籍信息新增成功 的本地化字符串。
        /// </summary>
        internal static string NationalityInfoInsertSuccess {
            get {
                return ResourceManager.GetString("NationalityInfoInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 国籍信息修改失败 的本地化字符串。
        /// </summary>
        internal static string NationalityInfoUpdateFailed {
            get {
                return ResourceManager.GetString("NationalityInfoUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 国籍信息修改成功 的本地化字符串。
        /// </summary>
        internal static string NationalityInfoUpdateSuccess {
            get {
                return ResourceManager.GetString("NationalityInfoUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请上传头像文件 的本地化字符串。
        /// </summary>
        internal static string PersonalAvatarFileNotNull {
            get {
                return ResourceManager.GetString("PersonalAvatarFileNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 头像文件大小不能超过 2MB 的本地化字符串。
        /// </summary>
        internal static string PersonalAvatarFileTooLarge {
            get {
                return ResourceManager.GetString("PersonalAvatarFileTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 头像文件格式不支持，仅支持 .png、.jpg、.jpeg 的本地化字符串。
        /// </summary>
        internal static string PersonalAvatarInvalidImageFormat {
            get {
                return ResourceManager.GetString("PersonalAvatarInvalidImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个人信息修改失败 的本地化字符串。
        /// </summary>
        internal static string PersonalUpdateFailed {
            get {
                return ResourceManager.GetString("PersonalUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个人信息修改成功 的本地化字符串。
        /// </summary>
        internal static string PersonalUpdateSuccess {
            get {
                return ResourceManager.GetString("PersonalUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传失败 的本地化字符串。
        /// </summary>
        internal static string PersonalUploadFailed {
            get {
                return ResourceManager.GetString("PersonalUploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传成功 的本地化字符串。
        /// </summary>
        internal static string PersonalUploadSuccess {
            get {
                return ResourceManager.GetString("PersonalUploadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码长度需为 8–16 位，并包含大小写字母、数字及特殊字符 的本地化字符串。
        /// </summary>
        internal static string PersonalValidationPassWrodError {
            get {
                return ResourceManager.GetString("PersonalValidationPassWrodError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所属部门 的本地化字符串。
        /// </summary>
        internal static string UserExcel_DepartmentName {
            get {
                return ResourceManager.GetString("UserExcel_DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱 的本地化字符串。
        /// </summary>
        internal static string UserExcel_Email {
            get {
                return ResourceManager.GetString("UserExcel_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 女 的本地化字符串。
        /// </summary>
        internal static string UserExcel_GenderFemale {
            get {
                return ResourceManager.GetString("UserExcel_GenderFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 男 的本地化字符串。
        /// </summary>
        internal static string UserExcel_GenderMale {
            get {
                return ResourceManager.GetString("UserExcel_GenderMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 性别 的本地化字符串。
        /// </summary>
        internal static string UserExcel_GenderName {
            get {
                return ResourceManager.GetString("UserExcel_GenderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入职日期 的本地化字符串。
        /// </summary>
        internal static string UserExcel_HireDate {
            get {
                return ResourceManager.GetString("UserExcel_HireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在职 的本地化字符串。
        /// </summary>
        internal static string UserExcel_IsEmployedCurrent {
            get {
                return ResourceManager.GetString("UserExcel_IsEmployedCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 离职 的本地化字符串。
        /// </summary>
        internal static string UserExcel_IsEmployedFormer {
            get {
                return ResourceManager.GetString("UserExcel_IsEmployedFormer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否在职 的本地化字符串。
        /// </summary>
        internal static string UserExcel_IsEmployedName {
            get {
                return ResourceManager.GetString("UserExcel_IsEmployedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否冻结 的本地化字符串。
        /// </summary>
        internal static string UserExcel_IsFreezeName {
            get {
                return ResourceManager.GetString("UserExcel_IsFreezeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正常 的本地化字符串。
        /// </summary>
        internal static string UserExcel_IsFreezeNormal {
            get {
                return ResourceManager.GetString("UserExcel_IsFreezeNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冻结 的本地化字符串。
        /// </summary>
        internal static string UserExcel_IsReviewFrozen {
            get {
                return ResourceManager.GetString("UserExcel_IsReviewFrozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否签核 的本地化字符串。
        /// </summary>
        internal static string UserExcel_IsReviewName {
            get {
                return ResourceManager.GetString("UserExcel_IsReviewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        internal static string UserExcel_IsReviewNorequired {
            get {
                return ResourceManager.GetString("UserExcel_IsReviewNorequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        internal static string UserExcel_IsReviewRequired {
            get {
                return ResourceManager.GetString("UserExcel_IsReviewRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 国籍 的本地化字符串。
        /// </summary>
        internal static string UserExcel_NationalityName {
            get {
                return ResourceManager.GetString("UserExcel_NationalityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电话号码 的本地化字符串。
        /// </summary>
        internal static string UserExcel_PhoneNumber {
            get {
                return ResourceManager.GetString("UserExcel_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 职级 的本地化字符串。
        /// </summary>
        internal static string UserExcel_PositionName {
            get {
                return ResourceManager.GetString("UserExcel_PositionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户信息 的本地化字符串。
        /// </summary>
        internal static string UserExcel_UserInfo {
            get {
                return ResourceManager.GetString("UserExcel_UserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户姓名（中文） 的本地化字符串。
        /// </summary>
        internal static string UserExcel_UserNameCn {
            get {
                return ResourceManager.GetString("UserExcel_UserNameCn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户姓名（英文） 的本地化字符串。
        /// </summary>
        internal static string UserExcel_UserNameEn {
            get {
                return ResourceManager.GetString("UserExcel_UserNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户工号 的本地化字符串。
        /// </summary>
        internal static string UserExcel_UserNo {
            get {
                return ResourceManager.GetString("UserExcel_UserNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请上传头像文件 的本地化字符串。
        /// </summary>
        internal static string UserInfoAvatarFileNotNull {
            get {
                return ResourceManager.GetString("UserInfoAvatarFileNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 头像文件大小不能超过 2MB 的本地化字符串。
        /// </summary>
        internal static string UserInfoAvatarFileTooLarge {
            get {
                return ResourceManager.GetString("UserInfoAvatarFileTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 头像文件格式不支持，仅支持 .png、.jpg、.jpeg 的本地化字符串。
        /// </summary>
        internal static string UserInfoAvatarInvalidImageFormat {
            get {
                return ResourceManager.GetString("UserInfoAvatarInvalidImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户信息删除失败 的本地化字符串。
        /// </summary>
        internal static string UserInfoDeleteFailed {
            get {
                return ResourceManager.GetString("UserInfoDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户信息删除成功 的本地化字符串。
        /// </summary>
        internal static string UserInfoDeleteSuccess {
            get {
                return ResourceManager.GetString("UserInfoDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户信息新增失败 的本地化字符串。
        /// </summary>
        internal static string UserInfoInsertFailed {
            get {
                return ResourceManager.GetString("UserInfoInsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户信息新增成功 的本地化字符串。
        /// </summary>
        internal static string UserInfoInsertSuccess {
            get {
                return ResourceManager.GetString("UserInfoInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户信息修改失败 的本地化字符串。
        /// </summary>
        internal static string UserInfoUpdateFailed {
            get {
                return ResourceManager.GetString("UserInfoUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户信息修改成功 的本地化字符串。
        /// </summary>
        internal static string UserInfoUpdateSuccess {
            get {
                return ResourceManager.GetString("UserInfoUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传失败 的本地化字符串。
        /// </summary>
        internal static string UserInfoUploadFailed {
            get {
                return ResourceManager.GetString("UserInfoUploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传成功 的本地化字符串。
        /// </summary>
        internal static string UserInfoUploadSuccess {
            get {
                return ResourceManager.GetString("UserInfoUploadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工号或账号已存在，请重新输入 的本地化字符串。
        /// </summary>
        internal static string UserInfoUserNoRepat {
            get {
                return ResourceManager.GetString("UserInfoUserNoRepat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码长度需为 8–16 位，并包含大小写字母、数字及特殊字符 的本地化字符串。
        /// </summary>
        internal static string UserInfoValidationPassWrodError {
            get {
                return ResourceManager.GetString("UserInfoValidationPassWrodError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 职业信息删除失败 的本地化字符串。
        /// </summary>
        internal static string UserLaborDeleteFailed {
            get {
                return ResourceManager.GetString("UserLaborDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 职业信息删除成功 的本地化字符串。
        /// </summary>
        internal static string UserLaborDeleteSuccess {
            get {
                return ResourceManager.GetString("UserLaborDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 职业信息新增失败 的本地化字符串。
        /// </summary>
        internal static string UserLaborInsertFailed {
            get {
                return ResourceManager.GetString("UserLaborInsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 职业信息新增成功 的本地化字符串。
        /// </summary>
        internal static string UserLaborInsertSuccess {
            get {
                return ResourceManager.GetString("UserLaborInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 职业信息修改失败 的本地化字符串。
        /// </summary>
        internal static string UserLaborUpdateFailed {
            get {
                return ResourceManager.GetString("UserLaborUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 职业信息修改成功 的本地化字符串。
        /// </summary>
        internal static string UserLaborUpdateSuccess {
            get {
                return ResourceManager.GetString("UserLaborUpdateSuccess", resourceCulture);
            }
        }
    }
}
