//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemAdmin.Localization.CustMat.CustMatBasicInfo {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemAdmin.Localization.CustMat.CustMatBasicInfo.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 删除客户信息失败 的本地化字符串。
        /// </summary>
        internal static string CustomerInfoDeleteFailed {
            get {
                return ResourceManager.GetString("CustomerInfoDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除客户信息成功 的本地化字符串。
        /// </summary>
        internal static string CustomerInfoDeleteSuccess {
            get {
                return ResourceManager.GetString("CustomerInfoDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增客户信息失败 的本地化字符串。
        /// </summary>
        internal static string CustomerInfoInsertFailed {
            get {
                return ResourceManager.GetString("CustomerInfoInsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增客户信息成功 的本地化字符串。
        /// </summary>
        internal static string CustomerInfoInsertSuccess {
            get {
                return ResourceManager.GetString("CustomerInfoInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改客户信息失败 的本地化字符串。
        /// </summary>
        internal static string CustomerInfoUpdateFailed {
            get {
                return ResourceManager.GetString("CustomerInfoUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改客户信息成功 的本地化字符串。
        /// </summary>
        internal static string CustomerInfoUpdateSuccess {
            get {
                return ResourceManager.GetString("CustomerInfoUpdateSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 新增料号信息成功 的本地化字符串。
        /// </summary>
        internal static string PartNumberInfoInsertSuccess {
            get {
                return ResourceManager.GetString("PartNumberInfoInsertSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 新增料号信息失败 的本地化字符串。
        /// </summary>
        internal static string PartNumberInfoInsertFailed {
            get {
                return ResourceManager.GetString("PartNumberInfoInsertFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 删除料号信息成功 的本地化字符串。
        /// </summary>
        internal static string PartNumberInfoDeleteSuccess {
            get {
                return ResourceManager.GetString("PartNumberInfoDeleteSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 删除料号信息失败 的本地化字符串。
        /// </summary>
        internal static string PartNumberInfoDeleteFailed {
            get {
                return ResourceManager.GetString("PartNumberInfoDeleteFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 修改料号信息成功 的本地化字符串。
        /// </summary>
        internal static string PartNumberInfoUpdateSuccess {
            get {
                return ResourceManager.GetString("PartNumberInfoUpdateSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 修改料号信息失败 的本地化字符串。
        /// </summary>
        internal static string PartNumberInfoUpdateFailed {
            get {
                return ResourceManager.GetString("PartNumberInfoUpdateFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 料号导入模板 的本地化字符串。
        /// </summary>
        internal static string PartNumberExcel_SheetName {
            get {
                return ResourceManager.GetString("PartNumberExcel_SheetName", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 料号 的本地化字符串。
        /// </summary>
        internal static string PartNumberExcel_PartNumber {
            get {
                return ResourceManager.GetString("PartNumberExcel_PartNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 品名 的本地化字符串。
        /// </summary>
        internal static string PartNumberExcel_PartNameCn {
            get {
                return ResourceManager.GetString("PartNumberExcel_PartNameCn", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 英文品名 的本地化字符串。
        /// </summary>
        internal static string PartNumberExcel_PartNameEn {
            get {
                return ResourceManager.GetString("PartNumberExcel_PartNameEn", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 规格 的本地化字符串。
        /// </summary>
        internal static string PartNumberExcel_Specification {
            get {
                return ResourceManager.GetString("PartNumberExcel_Specification", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 料号类型 的本地化字符串。
        /// </summary>
        internal static string PartNumberExcel_PartType {
            get {
                return ResourceManager.GetString("PartNumberExcel_PartType", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 物料分类 的本地化字符串。
        /// </summary>
        internal static string PartNumberExcel_Category {
            get {
                return ResourceManager.GetString("PartNumberExcel_Category", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 型号 的本地化字符串。
        /// </summary>
        internal static string PartNumberExcel_Model {
            get {
                return ResourceManager.GetString("PartNumberExcel_Model", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 图号 的本地化字符串。
        /// </summary>
        internal static string PartNumberExcel_DrawingNumber {
            get {
                return ResourceManager.GetString("PartNumberExcel_DrawingNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 版本 的本地化字符串。
        /// </summary>
        internal static string PartNumberExcel_Version {
            get {
                return ResourceManager.GetString("PartNumberExcel_Version", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 材质 的本地化字符串。
        /// </summary>
        internal static string PartNumberExcel_Material {
            get {
                return ResourceManager.GetString("PartNumberExcel_Material", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 基本单位 的本地化字符串。
        /// </summary>
        internal static string PartNumberExcel_BaseUnit {
            get {
                return ResourceManager.GetString("PartNumberExcel_BaseUnit", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 来源类型 的本地化字符串。
        /// </summary>
        internal static string PartNumberExcel_SourceType {
            get {
                return ResourceManager.GetString("PartNumberExcel_SourceType", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 制造商 的本地化字符串。
        /// </summary>
        internal static string PartNumberExcel_Manufacturer {
            get {
                return ResourceManager.GetString("PartNumberExcel_Manufacturer", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 制造商料号 的本地化字符串。
        /// </summary>
        internal static string PartNumberExcel_ManufacturerPartNumber {
            get {
                return ResourceManager.GetString("PartNumberExcel_ManufacturerPartNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 是否批号管制 的本地化字符串。
        /// </summary>
        internal static string PartNumberExcel_LotControl {
            get {
                return ResourceManager.GetString("PartNumberExcel_LotControl", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 启用状态 的本地化字符串。
        /// </summary>
        internal static string PartNumberExcel_Status {
            get {
                return ResourceManager.GetString("PartNumberExcel_Status", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        internal static string PartNumberExcel_Remark {
            get {
                return ResourceManager.GetString("PartNumberExcel_Remark", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 请上传导入文件 的本地化字符串。
        /// </summary>
        internal static string PartNumberImport_FileEmpty {
            get {
                return ResourceManager.GetString("PartNumberImport_FileEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Excel文件中未找到工作表 的本地化字符串。
        /// </summary>
        internal static string PartNumberImport_NoWorksheet {
            get {
                return ResourceManager.GetString("PartNumberImport_NoWorksheet", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Excel文件中至少需要一条数据 的本地化字符串。
        /// </summary>
        internal static string PartNumberImport_NoData {
            get {
                return ResourceManager.GetString("PartNumberImport_NoData", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 第{0}列列名不符，应为“{1}”，实际为“{2}”，请使用标准模板填写 的本地化字符串。
        /// </summary>
        internal static string PartNumberImport_HeaderMismatch {
            get {
                return ResourceManager.GetString("PartNumberImport_HeaderMismatch", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 列数量与模板不符，请使用标准模板填写 的本地化字符串。
        /// </summary>
        internal static string PartNumberImport_ColumnCountMismatch {
            get {
                return ResourceManager.GetString("PartNumberImport_ColumnCountMismatch", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 第{0}行【{1}】不能为空 的本地化字符串。
        /// </summary>
        internal static string PartNumberImport_RequiredFieldEmpty {
            get {
                return ResourceManager.GetString("PartNumberImport_RequiredFieldEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 第{0}行【{1}】的值“{2}”不在有效范围内 的本地化字符串。
        /// </summary>
        internal static string PartNumberImport_InvalidDictValue {
            get {
                return ResourceManager.GetString("PartNumberImport_InvalidDictValue", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 成功导入{0}条料号信息 的本地化字符串。
        /// </summary>
        internal static string PartNumberImport_Success {
            get {
                return ResourceManager.GetString("PartNumberImport_Success", resourceCulture);
            }
        }
    }
}
