//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemAdmin.Localization.SystemBasicMgmt.SystemMgmt {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemAdmin.Localization.SystemBasicMgmt.SystemMgmt.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 模块删除失败。 的本地化字符串。
        /// </summary>
        internal static string ModuleDeleteFailed {
            get {
                return ResourceManager.GetString("ModuleDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块删除成功。 的本地化字符串。
        /// </summary>
        internal static string ModuleDeleteSuccess {
            get {
                return ResourceManager.GetString("ModuleDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块新增失败。 的本地化字符串。
        /// </summary>
        internal static string ModuleInsertFailed {
            get {
                return ResourceManager.GetString("ModuleInsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块新增成功。 的本地化字符串。
        /// </summary>
        internal static string ModuleInsertSuccess {
            get {
                return ResourceManager.GetString("ModuleInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块信息修改失败。 的本地化字符串。
        /// </summary>
        internal static string ModuleUpdateFailed {
            get {
                return ResourceManager.GetString("ModuleUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块信息修改成功。 的本地化字符串。
        /// </summary>
        internal static string ModuleUpdateSuccess {
            get {
                return ResourceManager.GetString("ModuleUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一级菜单删除失败。 的本地化字符串。
        /// </summary>
        internal static string PMenuDeleteFailed {
            get {
                return ResourceManager.GetString("PMenuDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一级菜单删除成功。 的本地化字符串。
        /// </summary>
        internal static string PMenuDeleteSuccess {
            get {
                return ResourceManager.GetString("PMenuDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一级菜单新增失败。 的本地化字符串。
        /// </summary>
        internal static string PMenuInsertFailed {
            get {
                return ResourceManager.GetString("PMenuInsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一级菜单新增成功。 的本地化字符串。
        /// </summary>
        internal static string PMenuInsertSuccess {
            get {
                return ResourceManager.GetString("PMenuInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一级菜单修改失败。 的本地化字符串。
        /// </summary>
        internal static string PMenuUpdateFailed {
            get {
                return ResourceManager.GetString("PMenuUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一级菜单修改成功。 的本地化字符串。
        /// </summary>
        internal static string PMenuUpdateSuccess {
            get {
                return ResourceManager.GetString("PMenuUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色删除失败。 的本地化字符串。
        /// </summary>
        internal static string RoleDeleteFailed {
            get {
                return ResourceManager.GetString("RoleDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色删除成功。 的本地化字符串。
        /// </summary>
        internal static string RoleDeleteSuccess {
            get {
                return ResourceManager.GetString("RoleDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色新增失败。 的本地化字符串。
        /// </summary>
        internal static string RoleInsertFailed {
            get {
                return ResourceManager.GetString("RoleInsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色新增成功。 的本地化字符串。
        /// </summary>
        internal static string RoleInsertSuccess {
            get {
                return ResourceManager.GetString("RoleInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色菜单绑定失败。 的本地化字符串。
        /// </summary>
        internal static string RoleRoleMenuUpdateFailed {
            get {
                return ResourceManager.GetString("RoleRoleMenuUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色菜单绑定成功。 的本地化字符串。
        /// </summary>
        internal static string RoleRoleMenuUpdateSuccess {
            get {
                return ResourceManager.GetString("RoleRoleMenuUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色模块绑定失败。 的本地化字符串。
        /// </summary>
        internal static string RoleRoleModuleUpdateFailed {
            get {
                return ResourceManager.GetString("RoleRoleModuleUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色模块绑定成功。 的本地化字符串。
        /// </summary>
        internal static string RoleRoleModuleUpdateSuccess {
            get {
                return ResourceManager.GetString("RoleRoleModuleUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该角色已被用户使用，请先调整用户角色后再删除。 的本地化字符串。
        /// </summary>
        internal static string RoleRoleUsed {
            get {
                return ResourceManager.GetString("RoleRoleUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色修改失败。 的本地化字符串。
        /// </summary>
        internal static string RoleUpdateFailed {
            get {
                return ResourceManager.GetString("RoleUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色修改成功。 的本地化字符串。
        /// </summary>
        internal static string RoleUpdateSuccess {
            get {
                return ResourceManager.GetString("RoleUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 二级菜单删除失败。 的本地化字符串。
        /// </summary>
        internal static string SMenuDeleteFailed {
            get {
                return ResourceManager.GetString("SMenuDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 二级菜单删除成功。 的本地化字符串。
        /// </summary>
        internal static string SMenuDeleteSuccess {
            get {
                return ResourceManager.GetString("SMenuDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 二级菜单新增失败。 的本地化字符串。
        /// </summary>
        internal static string SMenuInsertFailed {
            get {
                return ResourceManager.GetString("SMenuInsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 二级菜单新增成功。 的本地化字符串。
        /// </summary>
        internal static string SMenuInsertSuccess {
            get {
                return ResourceManager.GetString("SMenuInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 二级菜单修改失败。 的本地化字符串。
        /// </summary>
        internal static string SMenuUpdateFailed {
            get {
                return ResourceManager.GetString("SMenuUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 二级菜单修改成功。 的本地化字符串。
        /// </summary>
        internal static string SMenuUpdateSuccess {
            get {
                return ResourceManager.GetString("SMenuUpdateSuccess", resourceCulture);
            }
        }
    }
}
