//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemAdmin.Localization.FormBusiness.FormBasicInfo {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemAdmin.Localization.FormBusiness.FormBasicInfo.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 删除控件失败 的本地化字符串。
        /// </summary>
        internal static string ControlInfoDeleteFailed {
            get {
                return ResourceManager.GetString("ControlInfoDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除控件成功 的本地化字符串。
        /// </summary>
        internal static string ControlInfoDeleteSuccess {
            get {
                return ResourceManager.GetString("ControlInfoDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增控件失败 的本地化字符串。
        /// </summary>
        internal static string ControlInfoInsertFailed {
            get {
                return ResourceManager.GetString("ControlInfoInsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增控件成功 的本地化字符串。
        /// </summary>
        internal static string ControlInfoInsertSuccess {
            get {
                return ResourceManager.GetString("ControlInfoInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改控件失败 的本地化字符串。
        /// </summary>
        internal static string ControlInfoUpdateFailed {
            get {
                return ResourceManager.GetString("ControlInfoUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改控件成功 的本地化字符串。
        /// </summary>
        internal static string ControlInfoUpdateSuccess {
            get {
                return ResourceManager.GetString("ControlInfoUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除表单组别失败 的本地化字符串。
        /// </summary>
        internal static string FormGroupDeleteFailed {
            get {
                return ResourceManager.GetString("FormGroupDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除表单组别成功 的本地化字符串。
        /// </summary>
        internal static string FormGroupDeleteSuccess {
            get {
                return ResourceManager.GetString("FormGroupDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增表单组别失败 的本地化字符串。
        /// </summary>
        internal static string FormGroupInsertFailed {
            get {
                return ResourceManager.GetString("FormGroupInsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增表单组别成功 的本地化字符串。
        /// </summary>
        internal static string FormGroupInsertSuccess {
            get {
                return ResourceManager.GetString("FormGroupInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改表单组别失败 的本地化字符串。
        /// </summary>
        internal static string FormGroupUpdateFailed {
            get {
                return ResourceManager.GetString("FormGroupUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改表单组别成功 的本地化字符串。
        /// </summary>
        internal static string FormGroupUpdateSuccess {
            get {
                return ResourceManager.GetString("FormGroupUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除表单类别失败 的本地化字符串。
        /// </summary>
        internal static string FormTypeDeleteFailed {
            get {
                return ResourceManager.GetString("FormTypeDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除表单类别成功 的本地化字符串。
        /// </summary>
        internal static string FormTypeDeleteSuccess {
            get {
                return ResourceManager.GetString("FormTypeDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除表单栏位失败 的本地化字符串。
        /// </summary>
        internal static string FormTypeFieldDeleteFailed {
            get {
                return ResourceManager.GetString("FormTypeFieldDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除表单栏位成功 的本地化字符串。
        /// </summary>
        internal static string FormTypeFieldDeleteSuccess {
            get {
                return ResourceManager.GetString("FormTypeFieldDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增表单栏位失败 的本地化字符串。
        /// </summary>
        internal static string FormTypeFieldInsertFailed {
            get {
                return ResourceManager.GetString("FormTypeFieldInsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增表单栏位成功 的本地化字符串。
        /// </summary>
        internal static string FormTypeFieldInsertSuccess {
            get {
                return ResourceManager.GetString("FormTypeFieldInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改表单栏位失败 的本地化字符串。
        /// </summary>
        internal static string FormTypeFieldUpdateFailed {
            get {
                return ResourceManager.GetString("FormTypeFieldUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改表单栏位成功 的本地化字符串。
        /// </summary>
        internal static string FormTypeFieldUpdateSuccess {
            get {
                return ResourceManager.GetString("FormTypeFieldUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增表单类别失败 的本地化字符串。
        /// </summary>
        internal static string FormTypeInsertFailed {
            get {
                return ResourceManager.GetString("FormTypeInsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增表单类别成功 的本地化字符串。
        /// </summary>
        internal static string FormTypeInsertSuccess {
            get {
                return ResourceManager.GetString("FormTypeInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改表单类别失败 的本地化字符串。
        /// </summary>
        internal static string FormTypeUpdateFailed {
            get {
                return ResourceManager.GetString("FormTypeUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改表单类别成功 的本地化字符串。
        /// </summary>
        internal static string FormTypeUpdateSuccess {
            get {
                return ResourceManager.GetString("FormTypeUpdateSuccess", resourceCulture);
            }
        }
    }
}
