//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemAdmin.Localization.FormBusiness.Forms {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemAdmin.Localization.FormBusiness.Forms.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 代理人「{0}」于 {1} 至 {2} 期间有待审批的请假申请，请改选其他代理人 的本地化字符串。
        /// </summary>
        internal static string AgentLeaveConflict {
            get {
                return ResourceManager.GetString("AgentLeaveConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 附件后缀不符合规范 的本地化字符串。
        /// </summary>
        internal static string AttachmentExtensionNotAllow {
            get {
                return ResourceManager.GetString("AttachmentExtensionNotAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择附件进行删除 的本地化字符串。
        /// </summary>
        internal static string AttachmentIdNotNull {
            get {
                return ResourceManager.GetString("AttachmentIdNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 附件不能为空 的本地化字符串。
        /// </summary>
        internal static string AttachmentNotNull {
            get {
                return ResourceManager.GetString("AttachmentNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 附件大小不得超过 25 MB 的本地化字符串。
        /// </summary>
        internal static string AttachmentSizeLimit {
            get {
                return ResourceManager.GetString("AttachmentSizeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 附件删除失败 的本地化字符串。
        /// </summary>
        internal static string DeleteAttachmentFailed {
            get {
                return ResourceManager.GetString("DeleteAttachmentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 年「{1}」余额不足，本次请假 {2} 天，可用余额 {3} 天 的本地化字符串。
        /// </summary>
        internal static string LeaveBalanceNotEnough {
            get {
                return ResourceManager.GetString("LeaveBalanceNotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无权申请此表单 的本地化字符串。
        /// </summary>
        internal static string NotCanApply {
            get {
                return ResourceManager.GetString("NotCanApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无权审批此表单 的本地化字符串。
        /// </summary>
        internal static string NotCanReview {
            get {
                return ResourceManager.GetString("NotCanReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无权查看此表单 的本地化字符串。
        /// </summary>
        internal static string NotCanView {
            get {
                return ResourceManager.GetString("NotCanView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无权作废此表单 的本地化字符串。
        /// </summary>
        internal static string NotCanVoided {
            get {
                return ResourceManager.GetString("NotCanVoided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代理人 的本地化字符串。
        /// </summary>
        internal static string PdfAgentUser {
            get {
                return ResourceManager.GetString("PdfAgentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 申请日期 的本地化字符串。
        /// </summary>
        internal static string PdfApplicantDate {
            get {
                return ResourceManager.GetString("PdfApplicantDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 附件 的本地化字符串。
        /// </summary>
        internal static string PdfAttachment {
            get {
                return ResourceManager.GetString("PdfAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名称 的本地化字符串。
        /// </summary>
        internal static string PdfAttachmentName {
            get {
                return ResourceManager.GetString("PdfAttachmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件大小 的本地化字符串。
        /// </summary>
        internal static string PdfAttachmentSize {
            get {
                return ResourceManager.GetString("PdfAttachmentSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 意见 的本地化字符串。
        /// </summary>
        internal static string PdfComment {
            get {
                return ResourceManager.GetString("PdfComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户部门 的本地化字符串。
        /// </summary>
        internal static string PdfDepartment {
            get {
                return ResourceManager.GetString("PdfDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表单编号 的本地化字符串。
        /// </summary>
        internal static string PdfFormNo {
            get {
                return ResourceManager.GetString("PdfFormNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请假总时数 的本地化字符串。
        /// </summary>
        internal static string PdfLeaveHours {
            get {
                return ResourceManager.GetString("PdfLeaveHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请假时间 的本地化字符串。
        /// </summary>
        internal static string PdfLeavePeriod {
            get {
                return ResourceManager.GetString("PdfLeavePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请假事由 的本地化字符串。
        /// </summary>
        internal static string PdfLeaveReason {
            get {
                return ResourceManager.GetString("PdfLeaveReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请假单 的本地化字符串。
        /// </summary>
        internal static string PdfLeaveTitle {
            get {
                return ResourceManager.GetString("PdfLeaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请假类型 的本地化字符串。
        /// </summary>
        internal static string PdfLeaveType {
            get {
                return ResourceManager.GetString("PdfLeaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂无数据 的本地化字符串。
        /// </summary>
        internal static string PdfNoData {
            get {
                return ResourceManager.GetString("PdfNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审批记录 的本地化字符串。
        /// </summary>
        internal static string PdfReviewRecord {
            get {
                return ResourceManager.GetString("PdfReviewRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审批结果 的本地化字符串。
        /// </summary>
        internal static string PdfReviewResult {
            get {
                return ResourceManager.GetString("PdfReviewResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审批步骤 的本地化字符串。
        /// </summary>
        internal static string PdfReviewStep {
            get {
                return ResourceManager.GetString("PdfReviewStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审批时间 的本地化字符串。
        /// </summary>
        internal static string PdfReviewTime {
            get {
                return ResourceManager.GetString("PdfReviewTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审批人 的本地化字符串。
        /// </summary>
        internal static string PdfReviewUser {
            get {
                return ResourceManager.GetString("PdfReviewUser", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 审批完成 的本地化字符串。
        /// </summary>
        internal static string PdfStampApproved {
            get {
                return ResourceManager.GetString("PdfStampApproved", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 用户姓名 的本地化字符串。
        /// </summary>
        internal static string PdfUserName {
            get {
                return ResourceManager.GetString("PdfUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户工号 的本地化字符串。
        /// </summary>
        internal static string PdfUserNo {
            get {
                return ResourceManager.GetString("PdfUserNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表单保存失败 的本地化字符串。
        /// </summary>
        internal static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表单保存成功 的本地化字符串。
        /// </summary>
        internal static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 附件上传失败 的本地化字符串。
        /// </summary>
        internal static string UploadFailed {
            get {
                return ResourceManager.GetString("UploadFailed", resourceCulture);
            }
        }
    }
}
