//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemAdmin.Localization.FormBusiness.Workflow {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemAdmin.Localization.FormBusiness.Workflow.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 核准完成通知 的本地化字符串。
        /// </summary>
        internal static string EmailNoticeApprovedTitle {
            get {
                return ResourceManager.GetString("EmailNoticeApprovedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前往审批 的本地化字符串。
        /// </summary>
        internal static string EmailNoticeBtnReview {
            get {
                return ResourceManager.GetString("EmailNoticeBtnReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登入系统 的本地化字符串。
        /// </summary>
        internal static string EmailNoticeBtnSignIn {
            get {
                return ResourceManager.GetString("EmailNoticeBtnSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看表单 的本地化字符串。
        /// </summary>
        internal static string EmailNoticeBtnViewForm {
            get {
                return ResourceManager.GetString("EmailNoticeBtnViewForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 链接 15 天内有效 的本地化字符串。
        /// </summary>
        internal static string EmailNoticeExpireHint {
            get {
                return ResourceManager.GetString("EmailNoticeExpireHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统自动发送，请勿回复 的本地化字符串。
        /// </summary>
        internal static string EmailNoticeFooter {
            get {
                return ResourceManager.GetString("EmailNoticeFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您好 {0} 的本地化字符串。
        /// </summary>
        internal static string EmailNoticeGreetingDefault {
            get {
                return ResourceManager.GetString("EmailNoticeGreetingDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尊敬的 {0} {1}，您好！ 的本地化字符串。
        /// </summary>
        internal static string EmailNoticeGreetingTemplate {
            get {
                return ResourceManager.GetString("EmailNoticeGreetingTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 女士 的本地化字符串。
        /// </summary>
        internal static string EmailNoticeGreetingTitleFemale {
            get {
                return ResourceManager.GetString("EmailNoticeGreetingTitleFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 先生 的本地化字符串。
        /// </summary>
        internal static string EmailNoticeGreetingTitleMale {
            get {
                return ResourceManager.GetString("EmailNoticeGreetingTitleMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 申请人 的本地化字符串。
        /// </summary>
        internal static string EmailNoticeLabelApplicant {
            get {
                return ResourceManager.GetString("EmailNoticeLabelApplicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 意见 的本地化字符串。
        /// </summary>
        internal static string EmailNoticeLabelComment {
            get {
                return ResourceManager.GetString("EmailNoticeLabelComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单号 的本地化字符串。
        /// </summary>
        internal static string EmailNoticeLabelFormNo {
            get {
                return ResourceManager.GetString("EmailNoticeLabelFormNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表单类型 的本地化字符串。
        /// </summary>
        internal static string EmailNoticeLabelFormType {
            get {
                return ResourceManager.GetString("EmailNoticeLabelFormType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结果 的本地化字符串。
        /// </summary>
        internal static string EmailNoticeLabelResult {
            get {
                return ResourceManager.GetString("EmailNoticeLabelResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前步骤 的本地化字符串。
        /// </summary>
        internal static string EmailNoticeLabelStep {
            get {
                return ResourceManager.GetString("EmailNoticeLabelStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 待审批通知 的本地化字符串。
        /// </summary>
        internal static string EmailNoticePendingTitle {
            get {
                return ResourceManager.GetString("EmailNoticePendingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 驳回通知 的本地化字符串。
        /// </summary>
        internal static string EmailNoticeRejectedTitle {
            get {
                return ResourceManager.GetString("EmailNoticeRejectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 核准 的本地化字符串。
        /// </summary>
        internal static string EmailNoticeResultApproved {
            get {
                return ResourceManager.GetString("EmailNoticeResultApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 驳回 的本地化字符串。
        /// </summary>
        internal static string EmailNoticeResultRejected {
            get {
                return ResourceManager.GetString("EmailNoticeResultRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 核准完成 的本地化字符串。
        /// </summary>
        internal static string EmailNoticeSubjectApproved {
            get {
                return ResourceManager.GetString("EmailNoticeSubjectApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 待审批 的本地化字符串。
        /// </summary>
        internal static string EmailNoticeSubjectPending {
            get {
                return ResourceManager.GetString("EmailNoticeSubjectPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已驳回 的本地化字符串。
        /// </summary>
        internal static string EmailNoticeSubjectRejected {
            get {
                return ResourceManager.GetString("EmailNoticeSubjectRejected", resourceCulture);
            }
        }
    }
}
